import { Container, Typography } from '@material-ui/core'
import React from 'react'

export const Home = () => {
  return (
    <>
    <Container maxWidth="xl">
     <Typography variant="caption">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo earum nulla est quas alias deleniti voluptates fugit, rerum quis ipsa. Provident eveniet quibusdam aliquam omnis consectetur, repellat dolor vel laboriosam dolorum officiis facilis reiciendis hic cum id delectus perspiciatis facere voluptatibus sapiente excepturi cumque optio temporibus magni debitis. Laboriosam, dolorem facere distinctio consectetur aliquid rerum eaque, exercitationem natus, praesentium accusantium quia sunt ex quo fuga odio aspernatur ratione autem magnam in pariatur at nulla unde? Vitae voluptatibus repellat dolorem, modi omnis a perferendis aliquid in quam corrupti exercitationem sit dolor quos temporibus suscipit architecto vel vero quia aperiam laborum facere recusandae totam veritatis eos? Minima esse laboriosam perspiciatis omnis culpa consequuntur cupiditate blanditiis aliquam aspernatur, accusantium nulla eos, voluptas quaerat molestias ipsa at. Nisi eveniet totam commodi voluptas molestias aliquam quam numquam tempora odio quasi fugiat asperiores sint maiores earum quos consequatur quibusdam, dolore, est quae doloribus quaerat accusamus blanditiis! Et, commodi nesciunt. Veritatis deserunt iure, perferendis sequi inventore rem unde. Itaque magni ex aliquam non ut reiciendis! Blanditiis voluptatum dolorum error velit minima quas neque molestiae, in laboriosam nam corporis consequuntur possimus aspernatur nihil adipisci totam ipsam nulla sapiente culpa non sequi deserunt perspiciatis. Numquam rem eligendi libero dolor!
     </Typography>
     <Typography variant="caption">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo earum nulla est quas alias deleniti voluptates fugit, rerum quis ipsa. Provident eveniet quibusdam aliquam omnis consectetur, repellat dolor vel laboriosam dolorum officiis facilis reiciendis hic cum id delectus perspiciatis facere voluptatibus sapiente excepturi cumque optio temporibus magni debitis. Laboriosam, dolorem facere distinctio consectetur aliquid rerum eaque, exercitationem natus, praesentium accusantium quia sunt ex quo fuga odio aspernatur ratione autem magnam in pariatur at nulla unde? Vitae voluptatibus repellat dolorem, modi omnis a perferendis aliquid in quam corrupti exercitationem sit dolor quos temporibus suscipit architecto vel vero quia aperiam laborum facere recusandae totam veritatis eos? Minima esse laboriosam perspiciatis omnis culpa consequuntur cupiditate blanditiis aliquam aspernatur, accusantium nulla eos, voluptas quaerat molestias ipsa at. Nisi eveniet totam commodi voluptas molestias aliquam quam numquam tempora odio quasi fugiat asperiores sint maiores earum quos consequatur quibusdam, dolore, est quae doloribus quaerat accusamus blanditiis! Et, commodi nesciunt. Veritatis deserunt iure, perferendis sequi inventore rem unde. Itaque magni ex aliquam non ut reiciendis! Blanditiis voluptatum dolorum error velit minima quas neque molestiae, in laboriosam nam corporis consequuntur possimus aspernatur nihil adipisci totam ipsam nulla sapiente culpa non sequi deserunt perspiciatis. Numquam rem eligendi libero dolor!
     </Typography>
     <Typography variant="caption">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo earum nulla est quas alias deleniti voluptates fugit, rerum quis ipsa. Provident eveniet quibusdam aliquam omnis consectetur, repellat dolor vel laboriosam dolorum officiis facilis reiciendis hic cum id delectus perspiciatis facere voluptatibus sapiente excepturi cumque optio temporibus magni debitis. Laboriosam, dolorem facere distinctio consectetur aliquid rerum eaque, exercitationem natus, praesentium accusantium quia sunt ex quo fuga odio aspernatur ratione autem magnam in pariatur at nulla unde? Vitae voluptatibus repellat dolorem, modi omnis a perferendis aliquid in quam corrupti exercitationem sit dolor quos temporibus suscipit architecto vel vero quia aperiam laborum facere recusandae totam veritatis eos? Minima esse laboriosam perspiciatis omnis culpa consequuntur cupiditate blanditiis aliquam aspernatur, accusantium nulla eos, voluptas quaerat molestias ipsa at. Nisi eveniet totam commodi voluptas molestias aliquam quam numquam tempora odio quasi fugiat asperiores sint maiores earum quos consequatur quibusdam, dolore, est quae doloribus quaerat accusamus blanditiis! Et, commodi nesciunt. Veritatis deserunt iure, perferendis sequi inventore rem unde. Itaque magni ex aliquam non ut reiciendis! Blanditiis voluptatum dolorum error velit minima quas neque molestiae, in laboriosam nam corporis consequuntur possimus aspernatur nihil adipisci totam ipsam nulla sapiente culpa non sequi deserunt perspiciatis. Numquam rem eligendi libero dolor!
     </Typography>
     <Typography variant="caption">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo earum nulla est quas alias deleniti voluptates fugit, rerum quis ipsa. Provident eveniet quibusdam aliquam omnis consectetur, repellat dolor vel laboriosam dolorum officiis facilis reiciendis hic cum id delectus perspiciatis facere voluptatibus sapiente excepturi cumque optio temporibus magni debitis. Laboriosam, dolorem facere distinctio consectetur aliquid rerum eaque, exercitationem natus, praesentium accusantium quia sunt ex quo fuga odio aspernatur ratione autem magnam in pariatur at nulla unde? Vitae voluptatibus repellat dolorem, modi omnis a perferendis aliquid in quam corrupti exercitationem sit dolor quos temporibus suscipit architecto vel vero quia aperiam laborum facere recusandae totam veritatis eos? Minima esse laboriosam perspiciatis omnis culpa consequuntur cupiditate blanditiis aliquam aspernatur, accusantium nulla eos, voluptas quaerat molestias ipsa at. Nisi eveniet totam commodi voluptas molestias aliquam quam numquam tempora odio quasi fugiat asperiores sint maiores earum quos consequatur quibusdam, dolore, est quae doloribus quaerat accusamus blanditiis! Et, commodi nesciunt. Veritatis deserunt iure, perferendis sequi inventore rem unde. Itaque magni ex aliquam non ut reiciendis! Blanditiis voluptatum dolorum error velit minima quas neque molestiae, in laboriosam nam corporis consequuntur possimus aspernatur nihil adipisci totam ipsam nulla sapiente culpa non sequi deserunt perspiciatis. Numquam rem eligendi libero dolor!
     </Typography>
     <Typography variant="caption">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo earum nulla est quas alias deleniti voluptates fugit, rerum quis ipsa. Provident eveniet quibusdam aliquam omnis consectetur, repellat dolor vel laboriosam dolorum officiis facilis reiciendis hic cum id delectus perspiciatis facere voluptatibus sapiente excepturi cumque optio temporibus magni debitis. Laboriosam, dolorem facere distinctio consectetur aliquid rerum eaque, exercitationem natus, praesentium accusantium quia sunt ex quo fuga odio aspernatur ratione autem magnam in pariatur at nulla unde? Vitae voluptatibus repellat dolorem, modi omnis a perferendis aliquid in quam corrupti exercitationem sit dolor quos temporibus suscipit architecto vel vero quia aperiam laborum facere recusandae totam veritatis eos? Minima esse laboriosam perspiciatis omnis culpa consequuntur cupiditate blanditiis aliquam aspernatur, accusantium nulla eos, voluptas quaerat molestias ipsa at. Nisi eveniet totam commodi voluptas molestias aliquam quam numquam tempora odio quasi fugiat asperiores sint maiores earum quos consequatur quibusdam, dolore, est quae doloribus quaerat accusamus blanditiis! Et, commodi nesciunt. Veritatis deserunt iure, perferendis sequi inventore rem unde. Itaque magni ex aliquam non ut reiciendis! Blanditiis voluptatum dolorum error velit minima quas neque molestiae, in laboriosam nam corporis consequuntur possimus aspernatur nihil adipisci totam ipsam nulla sapiente culpa non sequi deserunt perspiciatis. Numquam rem eligendi libero dolor!
     </Typography>
    </Container>
    </>
  )
}
